name: TimedWhitelist
version: '${project.version}'
main: com.person98.timedwhitelist.TimedWhitelist
api-version: 1.19
commands:
  timedwhitelist:
    description: Adds a player to the whitelist for a specific duration.
    permissions:
      timedwhitelist.add:
        description: Permission to add players to the whitelist
        default: op
      timedwhitelist.addtime:
        description: Permission to add time to a player's whitelist
        default: op
      timedwhitelist.removetime:
        description: Permission to remove time from a player's whitelist
        default: op
      timedwhitelist.remove:
        description: Permission to remove players from the whitelist
        default: op
      timedwhitelist.list:
        description: Permission to list players on the whitelist
        default: op
      timedwhitelist.list.all:
        description: Permission to list all players on the whitelist
        default: op
      timedwhitelist.toggle:
        description: Permission to toggle whitelist on and off
        default: op